spring:
#  실무에서는 프로젝트를 복사하지 않고 "프로파일 분리 방식"을 이용한다.
#  profiles:
#    active: dev

  datasource:
#    url: jdbc:mysql://localhost:3306/board_crud?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    # 위의 url은 로컬에서 사용 시, 밑의 url은 도커에서 사용, mysql-crud-container는 mysql 컨테이너의 이름
    url: jdbc:mysql://mysql-crud-container:3306/board_crud?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 100 # 배치전략을 위해 필요
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect